rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: cadvisor
    scrape_interval: 10s 
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.100.45:8080']
        labels:
          group: 'cadvisor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"